
[infra-init]
description = "Terraform init for production"
dir = "infra/prd"
run = "terraform init"

[infra-plan]
description = "Terraform plan for production"
dir = "infra/prd"
run = "terraform plan"

[infra-apply]
description = "Terraform apply for production"
dir = "infra/prd"
run = "terraform apply"
