openapi: hoge
info:
  title: All in oneの自分用スラックアプリ
  version: 0.1.0
components:
  schemas: {}
  parameters: {}
paths:
  /api/hello:
    get:
      responses:
        "200":
          description: Object with user data.
          content:
            application/json:
              schema:
                type: object
                properties: {}
